prateekbh/preact-material-components

src/CheckBox/CheckBox.js
Fixes checkbox alignment issue and #7
=> checkbox fix

README.md, src/CheckBox/CheckBox.js, src/FormField/FormField.js
=> Form field

Toolbar/index.js
=> breaking toolbar into components

package.json
See #28 Download not visible in npm
See https://docs.npmjs.com/files/package.json#people-fields-author-contributors
=> maintainers -> contributors

sample/home.jsx
=> import from '../Components/' -> '../'

Toolbar/index.js
=> new toolbar dom

LayoutGrid/LayoutGrid.jsx, LayoutGrid/index.js, componentsList.js, index.js, package.json, sample/home.jsx
* Adds LayoutGrid and LayoutGrid.Cell
* LayoutGrid.Cell can have values assigned for spans (all supported
versions), column order and alignment
* `package.json` scripts adjusted to be Windows-friendly
* Tweaks to sample app to include the grid and correct existing typo
=> Adds LayoutGrid to the available components

Elevation/Elevation.jsx, Elevation/index.js, LayoutGrid/index.js, List/List.jsx, List/index.js, Select/Select.jsx, Select/index.js, sample/home.jsx
=> List and card fixes

package.json
Closes #82
https://greenkeeper.io/
=> fix(package): update material-components-web to version 0.9.1

Components/Home/Home.jsx, Components/LayoutGridPage/LayoutGridPage.css, Components/LayoutGridPage/LayoutGridPage.jsx, Components/LayoutGridPage/sample.txt, copy-css.js, package.json
* LayoutGridPage added
* Supporting files updated to include LayoutGridPage
* `package.json` authors updated
=> Adds documentation for LayoutGrid component

README.md
* layout-grid went missing in the last update to README 😢
=> Puts layout-grid back in the README

Textfield/Textfield.jsx, Textfield/index.js
* Removes the hardcoded `type="text"`
* Adds `type` as a prop (for passwords, dates, etc)
* Removes duplicate `className`
=> Improvements to Textfield component

Components/TextfieldPage/TextfieldPage.jsx, package.json, public/app.css, public/app.js, public/vendor.js
* Adds doc and demo for using `props.type`
The styling of `TextfieldPage` seems to have gone a bit awry after `lint-staged` crept in. If you prefer I'll redo, although I think the `package.json` scripts need checking - the `lint` script is clearly wrong as `eslint` isn't a dependency and `src/` doesn't exist!
=> Documentation for Textfield change

Drawer/Drawer.jsx, package.json
=> Newdrawers

CssMigrationWebpackPlugin.js, Drawer/index.js, LinearProgress/LinearProgress.jsx, LinearProgress/index.js, Radio/index.js, Snackbar/Snackbar.jsx, Snackbar/index.js, Tabs/Tabs.jsx, Tabs/index.js, Textfield/Textfield.jsx, Textfield/index.js, componentsList.js, index.js, sample/home.jsx, sample/index.html, sample/material-components-web.js
=> adding linear progress

Drawer/Drawer.jsx, Drawer/index.js
@prateekbh Not sure what your formal process is, but tested this locally and it works.
Fixes #156
=> Remove double exports for PermanentDrawer

LinearProgress/index.js, README.md, Slider/Slider.jsx, Slider/index.js, Tabs/index.js, componentsList.js, index.js, sample/home.jsx
=> Add Slider component

IconToggle/IconToggle.jsx, index.js, package.json, sample/home.jsx
Icon-toggle component added. Fixes #148
=> Icon toggle

IconToggle/IconToggle.jsx, README.md, package.json, sample/home.jsx, sample/webpack.config.js
=> toggle icon fix

Card/Card.jsx
Adds ```Card.HorizontalBlock``` to be able to make horizontal layouts like shown on [this page](https://material-components-web.appspot.com/card.html).
=> Add Card.HorizontalBlock

Button/Button.jsx
=> Make a Button an anchor if it has an href prop

Dialog/Dialog.jsx, package.json, sample/home.jsx
=> fixing dialog styles

IconToggle/IconToggle.jsx
=> Added in onChange event and className extending

Slider/Slider.jsx
The Slider component was not updating when props changed. This update allows the component to be used properly in a controlled component manner.
=> Fixes Update issues with Slider component. 

Drawer/Drawer.jsx
- Permanent Drawer Header
- Permanent Drawer Content
- (and a fix for Persistent Drawer Content)
=> Add remaining drawer components

Dialog/Dialog.jsx
https://github.com/material-components/material-components-web/tree/master/packages/mdc-dialog#dialog-events
=> Add dialog accept and cancel events

Drawer/Drawer.jsx
@filoozom urgent request to approve the PR..
I need to do publish the new version and this one got left
=> drawer component bug fix

MaterialComponent.js
=> Fix MaterialComponent className

Toolbar/Toolbar.jsx, package.json
=> adding Toolbar js object

package.json
=> fix(package): update material-components-web to version 0.18.1

Button/Button.jsx
Add ```raised``` and ```unelevated``` button props from ```material-components-web``` version ```0.19.0``` (#228).
=> Add raised and unelevated button props

Textfield/Textfield.jsx
=> label bug fix

.eslintrc.yml, Card/Card.jsx, Dialog/Dialog.jsx, Drawer/Drawer.jsx, Select/Select.jsx, Toolbar/Toolbar.jsx, package.json, sample/home.jsx
This does following things:
- Sync ```eslint``` and ```prettier``` configs. This means that linting won't show errors for code fixed by ```prettier```.
- Make ```prettier``` mandatory, else travis builds will fail (added to ```test``` script)
- Run ```prettier``` on all files
Closes #243.
=> Enforce code style

.travis.yml, docs/package.json, docs/template.html
=> adding base tag in template

docs/src/routes/elevation/index.js, docs/src/routes/elevation/sample.txt
To be merged after #255 
fixes a small description and checks up our auto deploy
=> fixing description

README.md
Just try this and check whether all your apps are working fine
=> updated readme to inform cloners to use strictMath less loader option

Fab/Fab.jsx, sample/home.jsx
=> fixes fab for mdc0.21.0

Button/Button.jsx, sample/home.jsx, sample/index.html
=> fixing button for mdc0.21.0

docs/package.json, docs/src/routes/button/index.js, docs/src/routes/fab/index.js, docs/src/style/index.scss
temporary fix for minified code in docs
=> temporary fix for minified code example

docs/src/routes/drawer/sample.txt
=> Button added to open Drawer

README.md
sir, i have fixed documentation and demo link,please check
thanks
=> fixed documentation and demo link

docs/src/routes/drawer/index.js, docs/src/routes/drawer/sample.txt, docs/src/routes/drawer/style.scss
=> Demo of the Drawer

docs/src/routes/checkbox/index.js, docs/src/routes/checkbox/sample.txt
So that clicking on the label works
=> Fix Checkbox id in docs example

.gitignore, Drawer/Drawer.jsx, sample/home.jsx
=> Declarative drawer

docs/package-lock.json, docs/package.json, docs/src/routes/drawer/index.js, docs/src/routes/drawer/sample.txt, package-lock.json
=> updating drawer docs

Menu/Menu.jsx, package.json, sample/home.jsx
this adds a declarative `open` prop to menu and adds events as props too
=> making menu declarative

MaterialComponent.js
fixes  a small bug to support class as a prop
=> fixing class prop messup

Checkbox/Checkbox.jsx, LinearProgress/LinearProgress.jsx, sample/home.jsx
- declarative checkoff
- declarative linear progress
=> More declarative

Radio/Radio.jsx, sample/home.jsx
adding `checked` prop to radio
=> making radio checked prop declarative

CssMigrationWebpackPlugin.js, MaterialComponent.js, package.json, sample/webpack.config.js
Adds:
- *.js (```MaterialComponent.js``` and ```CssMigrationWebpackPlugin.js```)
- sample/webpack.config.js
to ```prettier```.
=> Run prettier on other js files

Slider/Slider.jsx, sample/home.jsx
Implemented Slider discrete option fixes #324
=> Added discrete option on Slider (#324)

Toolbar/Toolbar.jsx, package.json
=> fixing menu icon

docs/src/index.js
I think it's better this way, got a moment of confusion because it's named `Home` :sweat_smile:
=> Import components/app as App

docs/src/routes/checkbox/basic-example.txt, docs/src/routes/checkbox/controlled-example.txt, docs/src/routes/checkbox/indeterminate-example.txt, docs/src/routes/checkbox/index.js
Here's a preview of what the changes look like:
=> Added example code for different options to Checkbox component

docs/package.json
=> material components update

docs/src/routes/checkbox/sample.txt, docs/src/routes/layout-grid/style.scss
=> fixing docs

Textfield/Textfield.jsx
After MDC upgrade textfield was renamed to text-field, maybe we should also change Textfield to TextField @prateekbh?
=> Fixed Textfield after mdc upgrade

docs/package-lock.json, docs/src/routes/select/index.js
- added docs for additional Select props
- updated package-lock.json to 1.3.1
=> added props documentation for Select component

Icon/Icon.jsx, sample/home.jsx
=> fixed broken class prop on Icon

List/List.jsx, Select/Select.jsx, package.json
- fixes new `select` dom
- fixes dom of list
=> changes from 0.0.27

Select/Select.jsx, sample/home.jsx
Setting of "selectedText" to "hintText" (if "selectedIndex" === -1) needs to happen in `componentDidMount` as well as `componentDidUpdate`
=> set "selectedText" to "hintText" not only on update, but on load.

Drawer/Drawer.jsx, package.json
fixing drawer changes from 0.28
CHANGELOG: https://github.com/material-components/material-components-web/blob/master/CHANGELOG.md#breaking-changes
=> fixing drawer

List/List.jsx, List/index.d.ts
=> fixing list

Chips/Chips.jsx, Chips/index.d.ts, componentsList.js, index.js, sample/home.jsx
Issue: #585
I've implemented the `Chip` and `ChipSet` component. Currently there's not a lot to them, but I imagine they will be extended upon in the future.
=> feat(Chips): implement chips

docs/src/routes/linear-progress/indeterminate-sample.txt, docs/src/routes/linear-progress/index.js, docs/src/routes/linear-progress/progress-sample.txt, docs/src/routes/linear-progress/reversed-sample.txt
=> doc: Adding linear progress demo code

Select/Select.jsx, docs/src/routes/image-list/index.js, package.json
=> select bug fix

package-lock.json
* Doc changes (#742)
* fixing version number
* fixing env target
* changing docs language
* new deps (#741)
* new deps
* Sync with Prettier
* Sync with Prettier
* fixing docs pics
* fixing pics (#743)
* fixing pics
* Update package.json
* fixing pics
* Update docs (#785)
* fixing version number
* fixing env target
* changing docs language
* new deps (#741)
* new deps
* Sync with Prettier
* Sync with Prettier
* fixing docs pics
* fixing pics (#743)
* fixing pics
* Update package.json
* fixing pics
* upgrading to 34 (#744)
* upgrading to 34
* Sync with Prettier
* text field value support
* Sync with Prettier
* Sync with Prettier
* fixing tests
* Release docs (#790)
* fixing version number
* fixing env target
* changing docs language
* new deps (#741)
* new deps
* Sync with Prettier
* Sync …
=> Release (#793)

CHANGELOG.md, Typography/index.d.ts, package-lock.json, package.json
Typings for Typography were old and broken, this PR fixed that.
=> v1.4.5 - Fixed typings for Typography.

webpack.config.js
=> Don't bundle a copy of Preact into dist

docs/src/routes/home/invidual-component-sample.txt
The wrong package is being imported.
=> Fix code typo on homepage

ts/Base/MaterialComponent.ts, ts/Base/types.ts, ts/TextField/index.tsx
See https://github.com/prateekbh/preact-material-components/issues/970#issuecomment-416740564
=> Improved TypeScript typing for soft merge

.gitignore, ts/TextField/index.tsx
Removed unnecessary state argument for TextField
=> Remove unneeded argument to render for TextField

.npmignore, ts/TextField/index.tsx
Updates mdc's value on value change
=> Fixed value update for floating label

ts/Switch/index.tsx
=> Fixed value update on slider

ts/TextField/index.tsx
=> Avoid re-setting input.value when already set

docs/src/routes/drawer/sample.txt
=> fix(docs): typo in drawer doc

packages/dialog/src/index.tsx
https://github.com/dequelabs/axe-core/blame/develop/lib/commons/aria/index.js#L279
=> Dialog: aside > dialog

.gitignore, .travis.yml, packages/docs/applitools.config.js, packages/docs/cypress.json, packages/docs/cypress/integration/visual-test/button-test.spec.js, packages/docs/cypress/integration/visual-test/card-test.spec.js, packages/docs/cypress/integration/visual-test/dialog-test.spec.js, packages/docs/cypress/integration/visual-test/drawer-test.spec.js, packages/docs/cypress/integration/visual-test/elevation-test.spec.js, packages/docs/cypress/integration/visual-test/fab-test.spec.js, packages/docs/cypress/integration/visual-test/formfield-test.spec.js, packages/docs/cypress/integration/visual-test/homepage-test.spec.js, packages/docs/cypress/integration/visual-test/icon-test.spec.js, packages/docs/cypress/integration/visual-test/iconbutton-test.spec.js, packages/docs/cypress/integration/visual-test/imagelist-test.spec.js, packages/docs/cypress/integration/visual-test/layout-grid-test.spec.js, packages/docs/cypress/integration/visual-test/linearprogress-test.spec.js, packages/docs/cypress/integration/visual-test/list-test.spec.js, packages/docs/cypress/integration/visual-test/menu-test.spec.js, packages/docs/cypress/integration/visual-test/snackbar-test.spec.js, packages/docs/cypress/plugins/index.js, packages/docs/cypress/support/commands.js, packages/docs/cypress/support/index.js, packages/docs/cypress/utils/utils.js, packages/docs/package.json, packages/docs/src/components/app/index.js, packages/docs/src/routes/dialog/index.js, packages/docs/src/routes/menu/index.js
- Fixes #1282
Hello!
At times maintaining separate visual test cases becomes a tiring task so using your existing doc setup we tried coming up with something that can ease this process. So I chose to use [Cypress](https://www.cypress.io/) as the browser test harness, which Applitools has an SDK for. I started off with writing tests for some of the components so it's sort of a "smoke test" but you can add more if you'd like. 
Visual regression involves comparing the pixels visually like a human would, ideally ignoring differences that a human couldn't perceive e.g. 1 pixel changes, differences in how browsers render images, drop shadows, etc. to avoid false positives; but you can still do a strict 1:1 pixel match if that's your preference.
Applitools thankfully  [provides an …
=> Introducing Applitools and Cypress

packages/card/src/actions/button.tsx, packages/card/src/actions/icons.tsx, packages/card/src/actions/index.tsx, packages/card/src/media.tsx, packages/card/src/primary-action.tsx, packages/docs/cypress/utils/utils.js, packages/docs/src/routes/card/index.js, packages/docs/src/routes/fab/index.js, packages/fab/src/index.tsx, packages/fab/src/label.tsx
Fixes #1253 
- updated fab2.0
- updated docs
- reverted component names for card(realized this'll help us and devs have less renames)
=> adding fab2.0

packages/base/src/MaterialComponent.ts, packages/chip/package.json, packages/chip/src/icon.tsx, packages/chip/src/index.tsx, packages/docs/src/routes/chips/index.js
Fixes #1247 
Complies with #1293
- Added Chipset
- Fixed Exports
- Added `onSelectionChange` event.
- Added `proxyEventHandler` for ease of #1293
=> Updating Chips

packages/elevation/package.json, packages/elevation/yarn.lock
- Fixes #1252 
- No changes to actual TSX
=> upgrading elevation

packages/docs/src/routes/list/index.js, packages/list/package.json, packages/list/src/group/index.tsx, packages/list/src/index.tsx, packages/list/src/item/graphic.tsx, packages/list/src/item/index.tsx, packages/list/src/item/link.tsx, packages/list/src/text/index.tsx, packages/list/src/text/secondary.tsx
- Fixes #1259 
- confirms to #1293
=> upgrading list

packages/docs/cypress/integration/visual-test/line-ripple-test.spec.js, packages/line-ripple/package.json, packages/line-ripple/yarn.lock
- this'll need a force push as we do not hav a page for this to test
=> Upgrades line ripple

packages/docs/cypress/integration/visual-test/menu-test.spec.js, packages/docs/package.json, packages/docs/src/routes/menu/index.js, packages/menu/package.json, packages/menu/sass/index.scss, packages/menu/src/divider.ts, packages/menu/src/index.tsx, packages/menu/yarn.lock
- Fixes #1260 
- Confirms to #1293
=> upgrading menu to 2.0

packages/docs/cypress/integration/visual-test/slider-test.spec.js, packages/docs/src/routes/slider/index.js, packages/slider/package.json, packages/slider/src/index.tsx, packages/slider/yarn.lock
=> upgrading slider

packages/docs/cypress/integration/visual-test/snackbar-test.spec.js, packages/docs/src/routes/snackbar/index.js, packages/slider/yarn.lock, packages/snackbar/package.json, packages/snackbar/src/action.tsx, packages/snackbar/src/actions.tsx, packages/snackbar/src/dismiss.tsx, packages/snackbar/src/index.tsx, packages/snackbar/src/label.tsx, packages/snackbar/yarn.lock, packages/switch/package.json
fixes #1265 
- confirms to #1293
=> upgrading snackbar

packages/base/src/MaterialComponent.ts, packages/docs/cypress/integration/visual-test/typography-test.spec.js, packages/docs/src/components/app/index.js, packages/docs/src/components/app/style.scss, packages/docs/src/routes/typography/index.js, packages/docs/yarn.lock, packages/icon-button/yarn.lock, packages/line-ripple/yarn.lock, packages/linear-progress/yarn.lock, packages/list/yarn.lock, packages/menu/yarn.lock, packages/select/yarn.lock, packages/slider/yarn.lock, packages/typography/package.json, packages/typography/src/index.tsx, packages/typography/yarn.lock
Upgraded typography (fixes #1272)
=> Upgraded typography

packages/docs/cypress/integration/visual-test/textfield-test.spec.js, packages/textfield/package.json, packages/textfield/src/input.tsx, packages/textfield/yarn.lock
fixes #1269 
- should have more tests
=> Textfield2.0

packages/docs/cypress/integration/visual-test/top-app-bar-test.spec.js, packages/docs/src/routes/top-app-bar/index.js, packages/top-app-bar/package.json, packages/top-app-bar/src/index.tsx, packages/top-app-bar/yarn.lock
fixes #1271
- confirms to #1293
=> upgrading top-app-bar

packages/docs/src/routes/layout-grid/index.js, packages/docs/src/routes/layout-grid/sample.txt, packages/layout-grid/package.json, packages/layout-grid/src/index.tsx, packages/layout-grid/yarn.lock, packages/top-app-bar/yarn.lock
Fixes #1257
Linear layout is not yet available in 1.X or 2.X
=> Linear layout 2.0

packages/docs/src/routes/image-list/index.js
There are some error in ImageList of `docs`.
So I fixed it!
=> docs: fix ImageList CodeBlock error
