Checkbox/Checkbox.jsx
Checkbox/index.js
Dialog/Dialog.jsx
Dialog/index.js
Drawer/Drawer.jsx
Drawer/index.js
Menu/Menu.jsx
Menu/index.js
README.md
Radio/Radio.jsx
Select/Select.jsx
Select/index.js
Snackbar/Snackbar.jsx
Tabs/Tabs.jsx
Tabs/index.js
Textfield/Textfield.jsx
Textfield/index.js

As seen in #129, here is the PR.
Just destroying the underlying ```MDComponent``` in ```componentWillUnmount``` was not enough. I had to remove event handlers as well in ```Select```and ```Drawer``` components.
Thanks.

Cleanup MDComponents allocations and event handlers

---

Radio/Radio.jsx
Switch/Switch.jsx
Textfield/Textfield.jsx

Removes the ```className``` cast to string in Radio, Switch and Textfield components. Now an "undefined" class is not added to elements when no ```className``` is specified. This fixes #147.

Remove className cast to string

---

Card/Card.jsx

This works somewhat like the ```Elevation``` components. We can set the ```x``` prop to ```1dot5```, ```2``` or ```3```.
Those are not in ```_mdcProps``` because unless I'm missing something we can't use props starting with an integer.
Not quite sure if I should call the prop ```x``` or ```size```, and maybe we could add something like ```String(props.x).replace('.', 'dot')``` to allow using ```x="1.5"``` instead of ```x="1dot5"```, but that seems kind of overkill.
Fixes #182.

Add Card.MediaItem

---

Toolbar/Toolbar.jsx

From the [MDC Toolbar docs](https://material.io/components/web/catalog/toolbar):
> There are two types of icons, `mdc-toolbar__icon--menu` represents the left most icon in `mdc-toolbar` usually to the left of `mdc-toolbar__title`
This will allow fixing the left/right padding on toolbar icons. I'm working on updating the demo/docs site. (AFAIK a release has to be made before I can compile the docs site?)

Add menu prop to Toolbar

---

Select/Select.jsx

Currently, when adding/removing children, the Select becomes blank, as the selectedIndex is reset. Also, if there are no children initially, the Select has a width of 0.
With these changes, when children are added/removed:
- Update `selectedIndex`
- Call `resize()` (as recommended by the [MDC Select docs](https://material.io/components/web/catalog/input-controls/select-menus/#using-the-foundation-class))

Fix dynamically updating Select's children

---

Select/Select.jsx

When using `<Select basic={true} />` it throws an error:
```
TypeError: Cannot read property 'unlisten' of undefined
at Select_Select.componentWillUnmount
```

Fix Select throwing error on componentWillUnmount if using 'basic'

---

MaterialComponent.js

From [comment](https://github.com/prateekbh/preact-material-components/pull/217#issuecomment-325885255) on #217:
It changed it so the classes were applied to className, but when there is already a className on the component, the material classes weren't added.
For example, `<Toolbar className="mdc-theme--dark">` only has `mdc-theme--dark` class in the rendered HTML instead of `mdc-theme--dark mdc-toolbar`.
I think this is because Preact [duplicates the class and className attributes](https://github.com/developit/preact/blob/33fc697ac11762a1cb6e71e9847670d047af7ce5/src/dom/index.js#L36). When I re-add the original line it fixes the problem.

Fix applying CSS on components with user-defined className

---

.travis.yml

Changes three things:
- Make sure to deploy the right folder (hopefully environment variables are supported there, documentation is not quite clear on that)
- Only deploy for NodeJS 8
- Only deploy when we are actually testing docs and not the root repo

Only deploy for NodeJS 8 and docs environment

---

MaterialComponent.js

Example: `<Card.Title class="foo" />`
Currently only `className` is supported.

Support custom `class` prop

---

docs/src/routes/button/index.js

I noticed while looking shortly through the docs that there was a typo with `in` and `it`.

fix(docs): fix spelling in the description of the button component.

---

Select/Select.jsx
docs/src/routes/select/index.js
sample/home.jsx

This addresses an issue where passing -1 as `selectedIndex` would cause `hintText` to be hidden. The preferred method to _clear_ a selection is now to pass `selectedIndex={1}` instead of `selectedIndex={null}`. 
`selectedIndex={null}` leaves `aria-selected=true`

Select - fix "unselected" state

---

Checkbox/index.d.ts
Dialog/index.d.ts
GridList/GridList.jsx
GridList/index.d.ts
Icon/index.d.ts
IconToggle/index.d.ts
LayoutGrid/index.d.ts
LinearProgress/LinearProgress.jsx
LinearProgress/index.d.ts
List/index.d.ts
Menu/index.d.ts
Select/index.d.ts
Slider/index.d.ts
Snackbar/index.d.ts
Switch/index.d.ts
TextField/index.d.ts
docs/src/routes/elevation/index.js
docs/src/routes/form-field/sample.txt
docs/src/routes/icon-toggle/sample.txt
docs/src/routes/select/sample.txt
docs/src/routes/textfield/index.js
docs/src/routes/textfield/sample.txt

Some typing fixes / improvements & also some fixes to docs and samples (I'm going through the docs and testing the typings with the samples so found some issues there).
Prop `disabled?: boolean` is redundant, since it's inherited from HTMLAttributes.
There are more coming later, but started this PR already so you can see some progress.
ping @YePpHa can you check this out also?

Typescript declaration improvements

---

Drawer/Drawer.jsx
Drawer/index.d.ts
MaterialComponentsWeb.d.ts
Menu/Menu.jsx
Menu/index.d.ts
Slider/Slider.jsx
Slider/index.d.ts

Resolves: #476.
All the event listeners will now pass the Event object as an argument to make it consistent for all the event listeners.
__Breaking change__
The events `onChange` and `onInput` will pass the event object instead of the value from `MDCComponent`. To still allow easy access to the value of the slider I've added the method `getValue`.

Made all event listeners consistent to always return Event

---

List/List.jsx

It seems the generated css classname for `ListSecondaryText` has been updated from `list-item__text__secondary-text` to `list-item__secondary-text`, which would cause wrong rendering of `ListSecondaryText`.
Might be relevant with these? 
https://github.com/material-components/material-components-web/pull/1877
https://github.com/material-components/material-components-web/pull/1660

List: update css classname of ListSecondaryText

---

Select/Select.jsx
docs/src/routes/select/index.js
sample/home.jsx
sample/webpack.config.js

Resolves: [#552](https://github.com/prateekbh/preact-material-components/issues/552)
Changes:
- Add `selected` and `disabled` props to the select options (extended ListItem as it's not feature of ListItem).
- Update some of the HTML elements to include the `tabindex` attribute (see https://github.com/material-components/material-components-web/blob/master/packages/mdc-select/README.md).
- `mdc-select__label--float-above` is added to the select label (`hintText`) whenever `selectedIndex` is not `-1` and removes it if it's `-1`. This fix should be removed when [material-components-web#1810](https://github.com/material-components/material-components-web/issues/1810) has been resolved.
- Remove the code that calls `setSelectedTextContent()` as it's not needed anymore.
I've also updated the …

fix(select): fix some issues with the select component.

---

Checkbox/Checkbox.jsx
Menu/Menu.jsx
Menu/index.d.ts
Select/Select.jsx
Select/index.d.ts
sample/home.jsx

See [v0.30.0/CHANGELOG.md](https://github.com/material-components/material-components-web/blob/v0.30.0/CHANGELOG.md) for the breaking changes.
__Changes:__
_Select_
- Remove the `basic` prop as the css version of `mdc-select` element has been removed.
- Add `box` prop.
- Replace `.mdc-select__menu` with the `Menu` component.
_Menu_
- Change the value of componentName to `menu`.
- Change all references of `MDCSimpleMenu` to `MDCMenu`.
- Change `MDCSimpleMenu:selected` to `MDCMenu:selected`.
- Change `MDCSimpleMenu:cancel` to `MDCMenu:cancel`.
- Replace `.mdc-simple-menu` with `.mdc-menu`.
- Replace `.mdc-simple-menu__items` with `.mdc-menu__items`.
- Replace `.mdc-menu__items` with the `List` component.
_Checkbox_
- Replace `mdc-checkbox__checkmark__path` with …

v30 Update components to include the breaking changes

---

docs/scripts/test-travis.js

Would have failed with an error code either way, but it's cleaner like this.

Improve error handling for Travis test script

---

docs/src/routes/card/index.js
ts/TextField/index.tsx

As #873 is still under consideration and needs rework for the new build system, this aims at fixing the `valid` prop for TypeScript.

Added valid to TextFieldProps

---

ts/Select/index.tsx

selectedIndex is provided on e.target.selectedIndex, but the typings said it should be accessed through e.selectedIndex, thus not compiling when accessing e.target.selectedIndex

Fixed the select onchange method typings

---

ts/Switch/index.tsx

I've removed all updates of `MDComponent.value`, and used `mdcNotifyProps` instead, to make the switch respond to the change of `props.disabled` and `props.checked`.
I'm not sure why `MDComponent.value` is updated here, it is neither existing here in `@material/switch` nor documented.
https://github.com/material-components/material-components-web/blob/master/packages/mdc-switch/index.js
Correct me if I'm wrong.
fixes #1189

Switch: Use mdcNotifyProps

---

packages/base/build/index.ts
packages/docs/preact.config.js

Fixes #1283 
- Fixes the `sass-resolver` for windows.
- Also import/export for `preact.config.js` didn't work in windows so used node style exports.

Get docs working in windows

---

ts/Dialog/index.tsx

According to https://github.com/dequelabs/axe-core/blame/develop/lib/commons/aria/index.js#L279
an alertdialog should be of element type dialog or section.
Closes #1288

Dialog: change to dialog element

---

packages/dialog/src/index.tsx

Successor of https://github.com/prateekbh/preact-material-components/pull/1289
Before we merge this. From [MDN](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/section):
- Each <section> should be identified, typically by including a heading (`<h1>`-`<h6>` element) as a child of the <section> element.
- **Do not use the <section> element as a generic container**; this is what `<div>` is for, especially when the sectioning is only for styling purposes. A rule of thumb is that a section should logically appear in the outline of a document.
But that's just opinions (?), while the specs says that aria-role alertdialog must only be on `dialog` or `section` elements, so I guess that's the heaviest part.

2.0 dialog axe compliant

---

packages/docs/cypress/integration/visual-test/button-test.spec.js
packages/docs/cypress/integration/visual-test/chip-test.spec.js
packages/docs/cypress/integration/visual-test/dialog-test.spec.js
packages/docs/cypress/integration/visual-test/drawer-test.spec.js
packages/docs/cypress/integration/visual-test/fab-test.spec.js
packages/docs/cypress/integration/visual-test/form-field-test.spec.js
packages/docs/cypress/integration/visual-test/homepage-test.spec.js
packages/docs/cypress/integration/visual-test/icon-button-test.spec.js
packages/docs/cypress/integration/visual-test/menu-test.spec.js
packages/docs/cypress/integration/visual-test/select-test.spec.js
packages/docs/cypress/integration/visual-test/slider-test.spec.js
packages/docs/cypress/integration/visual-test/tabs-test.spec.js
packages/docs/cypress/integration/visual-test/top-app-bar-test.spec.js
packages/docs/cypress/utils/utils.js

In cypress, sizeMode is deprecated.
So I replaced all of them to target.

fix: sizeMode => target

---

packages/select/src/basic-select.tsx

There is no setter of labelRef.
So labelRef is always `undefined`, and cannot executive this code:
```
protected updateSelection() {
...
const selectedIndex = this.MDComponent.selectedIndex;
if (selectedIndex === 0) {
if (this.labelRef) {
this.labelRef.classList.remove('mdc-floating-label--float-above');
}
} else {
if (this.labelRef) {
this.labelRef.classList.add('mdc-floating-label--float-above');
}
}
}
}
```
So I fix it!
before:
after:

fix: setLabelRef
